server:
  port: 8090 #端口
spring:
  application:
    name: usian-item-service #注册eureka的名字

  datasource: #配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.140:8066/usian?characterEncoding=UTF-8
    username: root
    password: 1111
    type: com.alibaba.druid.pool.DruidDataSource
  #配置redis集群端口和地址
  redis:
    cluster:
      nodes:
        - 192.168.50.133:7001
        - 192.168.50.133:7002
        - 192.168.50.133:7003
        - 192.168.50.133:7004
        - 192.168.50.133:7005
        - 192.168.50.133:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.50.128
    username: admin
    password: 1111
    virtual-host: /
#设置三种订阅模式手动ack
    listener:
      direct:
        acknowledge-mode: manual
  #设置work消息类型手动ack
      simple:
        acknowledge-mode: manual

#配置缓存首页商品分类的 key
portal_catresult_redis_key: portal_catresult_redis_key

#eureka注册中心的位置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#商品详情
ITEM_INFO: ITEM_INFO
BASE: BASE
DESC: DESC
PARAM: PARAM
ITEM_INFO_EXPIRE: 86400
SETNX_DESC_LOCK_KEY: SETNX_DESC_LOCK_KEY
SETNX_BASC_LOCK_KEY: SETNX_BASC_LOCK_KEY
SETNX_PARAM_LOCK_KEY: SETNX_PARAM_LOCK_KEY